version: '3.9'

services:
  cdn:
    container_name: skeleton-api-cdn
    image: registry.gitlab.com/kubide-crew/services/cdn-nginx:1.1.1
    ports:
      - "8081:80"
    volumes:
      - ../../artifacts/public:/var/www/assets/

  postgres:
    container_name: skeleton-api-postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'kubide'
      POSTGRES_PASSWORD: 'kubideMola'
    volumes:
      - ../../artifacts/postgres:/var/lib/postgresql/data/
    networks:
      - postgres

  pgadmin:
    container_name: skeleton-api-pgadmin
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'desarrollo@kubide.es'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "5050:80"
    networks:
      - postgres

#  grafana:
#    container_name: skeleton-api-grafana
#    image: "grafana/grafana:latest"
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    volumes:
#      - ../grafana/provisioning:/etc/grafana/provisioning
#      - grafana-data:/var/lib/grafana
#
#  loki:
#    container_name: skeleton-api-loki
#    image: "grafana/loki:latest"
#    restart: unless-stopped
#    user: "0"
#    command:
#      - '-config.file=/mnt/config/loki-config.yml'
#      - '-print-config-stderr'
#    ports:
#      - "3100:3100"
#    volumes:
#      - ../loki/loki-config.yml:/mnt/config/loki-config.yml
#      - loki-data:/loki
#
#  promtail:
#    container_name: skeleton-api-promtail
#    image: "grafana/promtail:latest"
#    restart: unless-stopped
#    command:
#      - '-config.file=/etc/promtail/promtail-config.yml'
#    volumes:
#      - ../promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
#      - promtail-data:/tmp
#      - ../../artifacts/logs:/tmp/log:ro

networks:
  postgres:
    driver: bridge

#volumes:
#  grafana-data:
#  loki-data:
#  promtail-data:
