version: '3'
services:
  core:
    build:
      context: ./
      dockerfile: pro.Dockerfile
    container_name: "skeleton-api-container"
    volumes:
      - ../../:/srv/service
      - ../../artifacts/public:/srv/public
      - ../../artifacts/logs:/tmp/log
    ports:
      - "8080"
    depends_on:
      - database
    links:
      - database
