positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: skeleton-api-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: skeleton-api-app
          __path__: /tmp/log/*log
